### PR TITLE
Begin supported PHP 7.3 and 8.1

### LINKED ISSUE #10: ord() passing only string parameter
Since PHP 7 requires that `ord` function parameter passing only string type.

The original notice message:
```
PHP Deprecated: ord(): Passing null to parameter #1 ($character) of type string is deprecated
```

### PR DESCRIPTION
**Pull request by icetee**
I upgrade phpunit for support >= PHP 7.3 and new testcases (thanks @kiboit). This PR fixes #10.

I think we will have to jump to the main version after merge this PR.

### CODE REVIEW

**Comment by glensc** [comment]
Don't hide your changes inside other commits. why have you reformatted some files? never mix formatting and logic changes to the same commit.

also, worth following:
- https://www.freshconsulting.com/insights/blog/atomic-commits/

**Comment by icetee** [comment]
I cut of atomic commits. This PR has breaking changes and drops the pre-PHP 7.4 world. If you approve this PR, I suggest jumping to the main version.

**Review by glensc — APPROVED** [review]

**Comment by LukeTowers** [comment]
If anyone's interested, @assetic-php will be dropping the usage of this package in favour of [wikimedia/minify](https://github.com/wikimedia/minify)'s JavaScriptMinifier. My recommendation would be to use that instead.

**Comment by glensc** [comment]
cherry-picked 78a79d6 and dec5687 to master branch.

5a3f33a7a04aac021e621d39e4e6158c5b497aaa seems to be commit from https://github.com/mrclay/jsmin-php/pull/9/files (change looks identical), but no credit given (reformatted as your git author)

**Comment by glensc** [comment]
rest of the changes not wanted or irrelevant

**Pull request closed without merging**
