### PR TITLE
Keep newline after string template

### PR DESCRIPTION
**Pull request by PLUS-RobertEhrenleitner**
Keep newline after string template. This addresses [issue #8](https://github.com/mrclay/jsmin-php/issues/8).

### CODE REVIEW

**Comment by glensc** [comment]
@PLUS-RobertEhrenleitner edit the PR and add link to issue, and issue add PR link as comment

**Comment by glensc** [comment]
Can you add new test case(s) for the scenario?

**Comment by PLUS-RobertEhrenleitner** [comment]
For addressing both issues, 8 and 15, I used the following program:
````
<?php
foreach (array('UnterminatedCommentException.php', 'UnterminatedRegExpException.php', 'UnterminatedStringException.php', 'JSMin.php') as $filename)
    include_once __DIR__ . '/jsmin-php/src/JSMin/' . $filename;

$js = <<<'EOF'
class TestClass {
    #a = "test"
    #b = 3
    #doSomething() {
        alert("Hallo " + this.#a)
    }

    testFunc1()  {
        this.#doSomething()
    }

    #testFunc2(b) {
        let la = "bla"
        let lb = 'blubb'
        let ah = `select *
from ${tbl}`
        let lc = `${la} ${lb}`

        this.#a = lc + " " + b
        if (this.#a.length > this.#b) this.testFunc1()
    }

    setB(v) {
        this.#b = v
    }

}
EOF;

$jsmin = new \JSMin\JSMin($js);
$minifiedJS = $jsmin->min();
echo $minifiedJS . PHP_EOL;
````

Deliberately appending semicolons at the line endings in the JS snippet should make the minifier keep everything in one line.

**Comment by glensc** [comment]
Tests go to `tests/Resources/minify` subdirs. see the testcase:
- https://github.com/mrclay/jsmin-php/blob/012afaff2979fd903eee33a32650d8f9fdcb4c95/tests/Tests/JSMin/JSMinTest.php#L125-L138

**Comment by PLUS-RobertEhrenleitner** [comment]
Oh my goodness, I cannot run the unit tests because in the file `phpunit/src/Util/Getopt.php`, in line 80, there it says
````
while (list($i, $arg) = each($args)) {
````
However, I have PHP 8.1 and the command `each` does no longer exist in this version, it should be done with a `foreach` loop. I will postpone this by some days.

**Comment by glensc** [comment]
I'm pretty sure you can just download phar version of PHPUnit rather the version from composer file.
- https://phar.phpunit.de/

**Comment by glensc** [comment]
You can use php 8.1 for tests now:
- https://github.com/mrclay/jsmin-php/pull/19

**Comment by glensc** [comment]
can you rebase instead of adding merge commit?

**Pull request closed without merging**
